### ISSUE TITLE
os_interface.c:updatePlatformInfo() does not deal with ISKL_GT2_WRK_DEVICE_F0_ID

### ISSUE THREAD

**Issue by igrche** [intel/cmrt#41]
I have the machine which device id is ISKL_GT2_WRK_DEVICE_F0_ID
But function os_interface.c:updatePlatformInfo() does not have case for this id, 
so CreatCmeDevice() aborted on this platform
Adding the following case fixed the issue:
$ git diff
diff --git a/src/os_interface.c b/src/os_interface.c
index cc5567b..513717c 100644
--- a/src/os_interface.c
+++ b/src/os_interface.c
@@ -1865,6 +1865,7 @@ static int updatePlatformInfo(PLATFORM \* pPlatform)
                break;
        case ISKL_GT2_DESK_DEVICE_F0_ID:
        case ISKL_GT2_DT_DEVICE_F0_ID:
- ```
    case ISKL_GT2_WRK_DEVICE_F0_ID:
          platform_setTypeAndFamily(pPlatform, PLATFORM_DESKTOP,
                                    IGFX_SKYLAKE, IGFX_GEN9_CORE,
  
  
                                    IGFX_GEN9_CORE);
  ```

**Comment by seanvk** [comment]
Merged

**Comment by igrche** [comment]
Verified
